### ISSUE TITLE
Design :: Appearance of the website

### ISSUE THREAD

**Issue by WenchuanLiliZhao** [WenchuanLiliZhao/WenchuanLiliZhao.GitHub.io#9]
## Subtasks

- [x] 12-grid 👺
- [x] Components
  - [x] Site banner
  - [x] Navigation Bar (general)
  - [x] Footer (general)
- [x] Pages
  - [x] Story page (also used as Overview and About page)
    - [x] Cover (try css: `align-item: center`)
    - [x] Timeline
    - [x] Chapter Title
  - [x] Blog page ⭐️
  - [x] Collections page ⭐️ (4 items/row)
